import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

// components
import Header from "../components/Header"
import ScrollManager from "../components/ScrollManager";

const JetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weights: [100, 200, 300, 400, 500, 600, 700, 800],
  variable: "--font-jetbrains-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={JetBrainsMono.variable}>
        <ScrollManager>
          <Header />
            {children}
        </ScrollManager>
      </body>
    </html>
  );
}
